Questão 1

In [14]:
import numpy as np
import random

arr = np.ones(8)
arr2 = np.random.randint(0,9,8)

arrsoma = arr + arr2

if arrsoma.sum() >= 40:
  mat = arrsoma.reshape(4,2)
else:
  mat = arrsoma.reshape(2,4)

print(mat)

[[1. 8. 4. 5.]
 [7. 3. 8. 2.]]


Questão 2

In [16]:
mat = np.zeros([2,2])

linhaRandom = random.randint(0,1)
colunaRandom = random.randint(0,1)

mat[linhaRandom,colunaRandom] = 1

ganhou = True

for i in range(3):
  jogadaLinha = int(input("Digite a linha: "))
  jogadaColuna = int(input("Digite a coluna: "))

  if mat[jogadaLinha, jogadaColuna] == 1:
    print("Game Over! :( Try Again!")
    ganhou = False
    break

if ganhou:
  print("Congratulations! You beat the game! :)1")





Digite a linha: 0
Digite a coluna: 1
Digite a linha: 1
Digite a coluna: 1
Game Over! :( Try Again!


Questão 3

In [ ]:
linhaRandom = random.randint(1,5)
colunaRandom = random.randint(1,5)

mat = np.empty([linhaRandom, colunaRandom])

linhas = mat.shape[0]
colunas = mat.shape[1]

mult = linhas * colunas

if mult % 2 == 0:
  print('Pode se tornar uma matriz com número par de elementos')
else:
  print ('Pode se tornar uma matriz com número ímpar de elementos')

Pode se tornar uma matriz com número par de elementos


Questão 4

In [ ]:
np.random.seed(10)

mtz = np.random.randint(1,50, [4, 4])

mediaColunas = mtz.mean(axis=0)
mediaLinhas = mtz.mean(axis=1)


print(f"Médias das colunas: {mediaColunas}")
print(f"Médias das linhas: {mediaLinhas}")

maiorValorColuna = mediaColunas.max()
maiorValorLinha = mediaLinhas.max()

print(f"Maior valor da média das colunas: {maiorValorColuna}")
print(f"Maior valor da média das linhas: {maiorValorLinha}")

print(np.unique(mtz, return_counts = True))

valores, contagens = np.unique(mtz, return_counts=True)

numeros2x = valores[contagens == 2]
print(numeros2x)

Médias das colunas: [28.   28.25 23.25 17.  ]
Médias das linhas: [16.  33.5 12.5 34.5]
Maior valor da média das colunas: 28.25
Maior valor da média das linhas: 34.5
(array([ 1,  9, 10, 16, 17, 26, 29, 30, 37, 41, 43, 49]), array([2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1]))
[ 1 10 30 37]


Questão 5

In [ ]:
mtz0 = np.zeros([3,3])
mtz1 = np.ones([3,3])

mtzSoma = (mtz0 + mtz1) * 5

arr = mtzSoma.reshape(9)
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5.]


Questão 6

In [ ]:
arr = np.arange(10, 30, 2)

print(f'Maior valor: {arr.max()} Índice: {arr.argmax()}')
print(f'Menor valor: {arr.min()} Índice: {arr.argmin()}')
print(f'Soma de todos os elementos: {arr.sum()}')

Maior valor: 28 Índice: 9
Menor valor: 10 Índice: 0
Soma de todos os elementos: 190


Questão 7

In [ ]:
np.random.seed(7)

arr = np.random.randint(1,10,5)
arr2 = np.random.randint(1,10,5)

arr3 = np.concatenate((arr,arr2))

mtz = arr3.reshape(2,5)

print(mtz)

[[5 7 4 4 8]
 [8 8 9 9 8]]
